# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketmongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='poketmon',
            name='location',
        ),
        migrations.AddField(
            model_name='capture',
            name='poketmon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmongo.Poketmon'),
        ),
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmongo.User'),
        ),
    ]
